---
abstract: 'Javascript Object Request Broker'
author:
  - 'Stevan Little <stevan.little@iinteractive.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  JS::Test::Base: 0
  Test::More: 0
  Test::WWW::Mechanize: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: JSORB
no_index:
  directory:
    - example
    - inc
    - t
requires:
  Buffer::Transactional: 0
  Class::Inspector: 0
  File::Copy: 0
  HTTP::Request: 0
  HTTP::Response: 0
  HTTP::Server::Simple: 0.34
  JS: 0
  JS::JSON: 0
  JS::jQuery: 0
  JSON::RPC::Common: 0.05
  Moose: 0
  MooseX::AttributeHelpers: 0
  MooseX::Params::Validate: 0
  MooseX::Traits: 0.06
  MooseX::Types::Path::Class: 0
  Path::Router: 0
  Set::Object: 0
  Text::SimpleTable: 0
  Try::Tiny: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
